# Generated by Django 5.2 on 2025-10-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_alter_run_athlete_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'In progress'), ('finished', 'Finished'), ('is_absent', 'Is absent')], default='is_absent', max_length=20),
        ),
    ]
