# Generated by Django 5.2 on 2025-10-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'In progress'), ('finished', 'Finished')], default='init', max_length=20),
        ),
    ]
