# Generated by Django 5.2 on 2025-10-19 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_alter_run_athlete_athleteinfo_run_athlete_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='athlete_info',
        ),
    ]
