# Generated by Django 5.2 on 2026-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_athleteinfo_goals_alter_athleteinfo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
